### ISSUE TITLE
Is it possible to click within the "share dialog"?

### ISSUE THREAD

**Issue by PatrickHuetter** [selendroid/selendroid#1040]
Is it possible with selendroid to click for example on "SMS/MMS" within the share dialog? If yes, is it possible to control the following app too (for example the sms app)?

Thank you very much and best regards
![click](https://cloud.githubusercontent.com/assets/1142911/13599143/dfbeeb14-e521-11e5-91c3-f0085da77e0c.jpg)

**Comment by operatiay** [comment]
Hallo Patrick,

if the dialogue has been created by your app (rather than by the OS) then you can interact with the dialogue the same way as you've been interacting with your app. Otherwise you can only use coordinates to click somewhere. This is obviously not reliable and not officially supported by selendroid.
Selendroid can't control the following app. However you could still use the same method of blindly interacting using coordinates.

hope this helps.

**Comment by PatrickHuetter** [comment]
Hi operatiay,
thank you for your answer. I already got this working like described in your post.

Best regards
