### ISSUE TITLE
Emulator never started when I ran demoproject-selendroid

### ISSUE THREAD

**Issue by bfhhxt0** [selendroid/selendroid#163]
I am trying to evaluate selendroid for automation in our shop, but running to an issue - emulator does not start during the test.

Here is the process:
- I have a working emulator working fine with command line: emulator -avd android16 
- I downdoaded: demoproject-selendroid-master.zip
- I unzip and and brought the project as maven project to eclipse (I use maven 3.1.1)
- I am able to do mvn clean install  no problem.
- I started java -jar selendroid-standalone-0.5.1-with-dependencies.jar -app employee-directory.apk -aut selendroid-test-app-0.6.0-SNAPSHOT.apk
- it recognized: 
  Nov 11, 2013 8:58:58 AM io.selendroid.server.model.DeviceStore addEmulators
  INFO: Adding: AndroidEmulator [screenSize=480x800, targetPlatform=ANDROID16, avdName=android16]
- able to see json from http://localhost:5555/wd/hub/status
- In eclipse I ran UserRegistrationTest.java - run as Junit test (Android Junit Test Launcher selection).
- then I see in eclipse under junit tab: org.openqa.sleenium.SessionNotCreatedException:Error occured while finding android device; Error occured while looking for devices/emulators.
  ...
  io.selendroid.demo.nativeui.UserRegistrationTest.setup(UserRegistrationTest.java:39) Caused by: io.selendroid.exceptions.SessionNotCreatedException:Error occured while finding andorid device: Error occurred while looking for device/emulators.
- I see from http://localhost:5555/wd/hub/status (repeat it aso many times):
  ...
  org.webbitserver.WebbitException: cannot send more responses than requests on [id: 0x7b1c661c, /127.0.0.1:62390 :> /127.0.0.1:5555
  ]
  ...

Here is my java -version:
java version "1.7.0_40-ea"
Java(TM) SE Runtime Environment (build 1.7.0_40-ea-b34)
Java HotSpot(TM) 64-Bit Server VM (build 24.0-b53, mixed mode)

So not sure where is my problem why the emulator not being launch.
Can you guys give some lead what to check  or to try on?

**Comment by geetabapat** [comment]
Hello,
I am new to this and I have ran into same error which is 
Caused by: io.selendroid.exceptions.SessionNotCreatedException: Error occured while finding android device: Error occurred while looking for devices/emulators.

I am using emulator so I have specified capa.setEmulator(true);
but I am unable to understand who would be starting emulator? Will my emulator get started automatically or do I have to start it.
Kindly send me link to tutorial which will guide me through set up of emulator and starting it so that I can test my first ever apk successfully.
