### ISSUE TITLE
info: return value from selendroid android server getting BLANK

### ISSUE THREAD

**Issue by irangtester** [selendroid/selendroid#784]
I am running my selendroid program , it runs properly without any error. I also pass login details of app. which I am testing. Once it logged in then it close App. automatically and in CMD is says : info: return value from selendroid android server.

But it is returning nothing, It is just blank , Why?

**Comment by operatiay** [comment]
What do you expect to see there?

**Comment by irangtester** [comment]
I want to login in and able to see dashboard of my app. App should not close once I tap in login. It should redirect me inside.

**Comment by operatiay** [comment]
set a breakpoint in your test code after you've clicked the login button and see what happens. your test might be successfully ending and the app closes due to this.

**Comment by irangtester** [comment]
I have tried that but that is also not giving me any clue.

**Comment by operatiay** [comment]
in this case I would write a logging line and place a break point on that line.

I think that you are not having any issue. Since your code doesn't do anything after clicking on the button, you won't see anything since the app doesn't have time to load the next screen.

please reopen if you experience any more issues, but with more details.

**Comment by irangtester** [comment]
But when I manually do login at that time it works. When running using selendroid at that time only it is getting close just after click on login.
