### ISSUE TITLE
Switch to webview is closing the app in Selendroid ver.14

### ISSUE THREAD

**Issue by fayizkc** [selendroid/selendroid#812]
While doing driver.switchTo().window("WEBVIEW") in Selendroid jar ver. 14 application getting close in the device. it is working fine up to ver. 13. Please check it out

**Comment by operatiay** [comment]
you need to provide more information if you want someone to have a look at your case. it works fine for me.

**Comment by fayizkc** [comment]
I just updated to the latest selendorid version (14) and executed my scripts. That time my application is closing when it is executing the step  driver.switchTo().window("WEBVIEW"); and I kept the Selendroid version 13 itself back. I will try it again and let you know if I am facing this issue in different application.
Thanks for the replay.

**Comment by attodorov** [comment]
I can confirm that whenever i switch to WEBVIEW, the app is just closed. I'm just doing a simple call:

driver.SwitchTo().Window("WEBVIEW");

(C#). I guess the same can be reproduced in Java. 

I tried both 0.13 and 0.14, and it's the same in 0.13 for me. 

Thanks

**Comment by attodorov** [comment]
Here is the complete output

/AndroidRuntime( 2401): Shutting down VM
D/AndroidRuntime( 2413): 
D/AndroidRuntime( 2413): >>>>>> AndroidRuntime START com.android.internal.os.RuntimeInit <<<<<<
D/AndroidRuntime( 2413): CheckJNI is ON
E/memtrack( 2413): Couldn't load memtrack module (No such file or directory)
E/android.os.Debug( 2413): failed to load memtrack module: -2
D/AndroidRuntime( 2413): Calling main entry com.android.commands.input.Input
I/Input   ( 2413): injectKeyEvent: KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x0, repeatCount=0, eventTime=131496, downTime=131496, deviceId=-1, source=0x101 }
I/Input   ( 2413): injectKeyEvent: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x0, repeatCount=0, eventTime=131496, downTime=131496, deviceId=-1, source=0x101 }
D/AndroidRuntime( 2413): Shutting down VM
E/art     ( 2413): Thread attaching while runtime is shutting down: Binder_1
I/AndroidRuntime( 2413): NOTE: attach of thread 'Binder_1' failed
D/AndroidRuntime( 2445): 
D/AndroidRuntime( 2445): >>>>>> AndroidRuntime START com.android.internal.os.RuntimeInit <<<<<<
D/AndroidRuntime( 2445): CheckJNI is ON
E/memtrack( 2445): Couldn't load memtrack module (No such file or directory)
E/android.os.Debug( 2445): failed to load memtrack module: -2
D/AndroidRuntime( 2445): Calling main entry com.android.commands.pm.Pm
D/AndroidRuntime( 2445): Shutting down VM
D/AndroidRuntime( 2456): 
D/AndroidRuntime( 2456): >>>>>> AndroidRuntime START com.android.internal.os.RuntimeInit <<<<<<
D/AndroidRuntime( 2456): CheckJNI is ON
E/memtrack( 2456): Couldn't load memtrack module (No such file or directory)
E/android.os.Debug( 2456): failed to load memtrack module: -2
D/AndroidRuntime( 2456): Calling main entry com.android.commands.pm.Pm
D/AndroidRuntime( 2456): Shutting down VM
D/AndroidRuntime( 2469): 
D/AndroidRuntime( 2469): >>>>>> AndroidRuntime START com.android.internal.os.RuntimeInit <<<<<<
D/AndroidRuntime( 2469): CheckJNI is ON
E/memtrack( 2469): Couldn't load memtrack module (No such file or directory)
E/android.os.Debug( 2469): failed to load memtrack module: -2
D/AndroidRuntime( 2469): Calling main entry com.android.commands.am.Am
I/ActivityManager( 1217): Force stopping enps.mobile.enpsmobilewrapper appid=10057 user=0: start instr
I/ActivityManager( 1217): Killing 1880:enps.mobile.enpsmobilewrapper/u0a57 (adj 0): stop enps.mobile.enpsmobilewrapper
W/InputDispatcher( 1217): channel '1868e7db enps.mobile.enpsmobilewrapper/enps.mobile.enpsmobilewrapper.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
E/InputDispatcher( 1217): channel '1868e7db enps.mobile.enpsmobilewrapper/enps.mobile.enpsmobilewrapper.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
I/WindowState( 1217): WIN DEATH: Window{1868e7db u0 enps.mobile.enpsmobilewrapper/enps.mobile.enpsmobilewrapper.MainActivity}
W/InputDispatcher( 1217): Attempted to unregister already unregistered input channel '1868e7db enps.mobile.enpsmobilewrapper/enps.mobile.enpsmobilewrapper.MainActivity (server)'
W/ActivityManager( 1217): Force removing ActivityRecord{2e710f10 u0 enps.mobile.enpsmobilewrapper/.MainActivity t5}: app died, no saved state
W/ActivityManager( 1217): Crash of app enps.mobile.enpsmobilewrapper running instrumentation ComponentInfo{io.selendroid.enps.mobile.enpsmobilewrapper/io.selendroid.server.ServerInstrumentation}
I/ActivityManager( 1217): Force stopping enps.mobile.enpsmobilewrapper appid=10057 user=0: finished inst
I/ActivityManager( 1217): Start proc enps.mobile.enpsmobilewrapper for added application enps.mobile.enpsmobilewrapper: pid=2480 uid=10057 gids={50057, 9997, 3003, 1028, 1015} abi=x86
W/ActivityManager( 1217): Spurious death for ProcessRecord{129f84af 1880:enps.mobile.enpsmobilewrapper/u0a57}, curProc for 1880: null
D/AndroidRuntime( 2469): Shutting down VM
I/art     ( 2480): Not late-enabling -Xcheck:jni (already on)
I/art     (  933): Explicit concurrent mark sweep GC freed 705(30KB) AllocSpace objects, 0(0B) LOS objects, 90% free, 110KB/1134KB, paused 1.060ms total 28.310ms
I/art     (  933): Explicit concurrent mark sweep GC freed 5(160B) AllocSpace objects, 0(0B) LOS objects, 90% free, 110KB/1134KB, paused 724us total 18.231ms
I/art     (  933): Explicit concurrent mark sweep GC freed 5(160B) AllocSpace objects, 0(0B) LOS objects, 90% free, 110KB/1134KB, paused 756us total 18.101ms
I/ActivityManager( 1217): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x34020000 cmp=enps.mobile.enpsmobilewrapper/.MainActivity} from uid 10057 on display 0
W/EGL_emulation( 1431): eglSurfaceAttrib not implemented
W/OpenGLRenderer( 1431): Failed to set EGL_SWAP_BEHAVIOR on surface 0xa6c3f7a0, error=EGL_SUCCESS
W/InputMethodManagerService( 1217): Got RemoteException sending setActive(false) notification to pid 1880 uid 10057
W/art     ( 2480): Suspending all threads took: 53.448ms
I/art     ( 2480): Background sticky concurrent mark sweep GC freed 751(74KB) AllocSpace objects, 1(16KB) LOS objects, 0% free, 27MB/27MB, paused 65.449ms total 121.393ms
I/Launcher( 1431): Deferring update until onResume
I/Launcher( 1431): Deferring update until onResume
I/Launcher( 1431): Deferring update until onResume
I/Launcher( 1431): Deferring update until onResume
D/        ( 2480): HostConnection::get() New Host Connection established 0xa61686d0, tid 2480
W/PackageManager( 1431): Failure retrieving resources for com.android.speechrecorder: Resource ID #0x0
W/PackageManager( 1431): Failure retrieving resources for com.android.speechrecorder: Resource ID #0x0
I/ActivityManager( 1217): Displayed enps.mobile.enpsmobilewrapper/.MainActivity: +668ms
I/LatinIME( 1331): Starting input. Cursor position = 0,0
W/EGL_emulation( 1331): eglSurfaceAttrib not implemented
W/OpenGLRenderer( 1331): Failed to set EGL_SWAP_BEHAVIOR on surface 0xa554b400, error=EGL_SUCCESS
D/TaskPersister( 1217): removeObsoleteFile: deleting file=5_task.xml
I/LatinIME( 1331): Starting input. Cursor position = 0,0
I/LatinIME( 1331): Starting input. Cursor position = 0,0
W/AudioTrack( 1217): AUDIO_OUTPUT_FLAG_FAST denied by client
I/ActivityManager( 1217): START u0 {cmp=enps.mobile.enpsmobilewrapper/.WebViewActivity (has extras)} from uid 10057 on display 0
I/art     ( 2480): Background sticky concurrent mark sweep GC freed 16761(886KB) AllocSpace objects, 3(48KB) LOS objects, 0% free, 55MB/55MB, paused 13.826ms total 37.256ms
I/WebViewFactory( 2480): Loading com.android.webview version 37 (1630668-x86) (code 100007)
I/LibraryLoader( 2480): Loading: webviewchromium
I/LibraryLoader( 2480): Time to load native libraries: 2 ms (timestamps 3944-3946)
I/LibraryLoader( 2480): Expected native library version number "",actual native library version number ""
V/WebViewChromiumFactoryProvider( 2480): Binding Chromium to main looper Looper (main, tid 1) {386d3104}
I/LibraryLoader( 2480): Expected native library version number "",actual native library version number ""
I/chromium( 2480): [INFO:library_loader_hooks.cc(106)] Chromium logging enabled: level = 0, default verbosity = 0
I/BrowserStartupController( 2480): Initializing chromium process, renderers=0
W/art     ( 2480): Attempt to remove local handle scope entry from IRT, ignoring
W/chromium( 2480): [WARNING:resource_bundle.cc(315)] locale_file_path.empty()
I/chromium( 2480): [INFO:aw_browser_main_parts.cc(63)] Load from apk succesful, fd=53 off=46092 len=2953
I/chromium( 2480): [INFO:aw_browser_main_parts.cc(78)] Loading webviewchromium.pak from, fd:54 off:228796 len:643667
W/AudioManagerAndroid( 2480): Requires BLUETOOTH permission
W/chromium( 2480): [WARNING:mailbox_synchronizer.cc(36)] MailboxSync not supported due to missing EGL image/fence support
W/chromium( 2480): [WARNING:data_reduction_proxy_settings.cc(403)] SPDY proxy OFF at startup
W/art     ( 2480): Attempt to remove local handle scope entry from IRT, ignoring
W/AwContents( 2480): onDetachedFromWindow called when already detached. Ignoring
W/art     ( 2480): Attempt to remove local handle scope entry from IRT, ignoring
W/art     ( 2480): Attempt to remove local handle scope entry from IRT, ignoring
W/chromium( 2480): [WARNING:proxy_service.cc(901)] PAC support disabled because there is no system implementation
I/ActivityManager( 1217): Displayed enps.mobile.enpsmobilewrapper/.WebViewActivity: +432ms
I/art     ( 2480): Rejecting re-init on previously-failed class java.lang.Class<io.selendroid.server.model.SelendroidWebDriver$ExtendedCordovaChromeClient>
I/art     ( 2480): Rejecting re-init on previously-failed class java.lang.Class<io.selendroid.server.model.SelendroidWebDriver$ExtendedCordovaChromeClient>
D/AndroidRuntime( 2480): Shutting down VM
E/SELENDROID( 2480): io.selendroid.server.UncaughtExceptionHandling$ExceptionDumper#uncaughtException:54 - Could not write crash log to: /storage/sdcard/appcrash.log
E/SELENDROID( 2480): java.io.FileNotFoundException: /storage/sdcard/appcrash.log: open failed: EACCES (Permission denied)
E/SELENDROID( 2480): 	at libcore.io.IoBridge.open(IoBridge.java:456)
E/SELENDROID( 2480): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
E/SELENDROID( 2480): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:72)
E/SELENDROID( 2480): 	at java.io.PrintWriter.<init>(PrintWriter.java:127)
E/SELENDROID( 2480): 	at io.selendroid.server.UncaughtExceptionHandling$ExceptionDumper.uncaughtException(UncaughtExceptionHandling.java:48)
E/SELENDROID( 2480): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
E/SELENDROID( 2480): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
E/SELENDROID( 2480): Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
E/SELENDROID( 2480): 	at libcore.io.Posix.open(Native Method)
E/SELENDROID( 2480): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
E/SELENDROID( 2480): 	at libcore.io.IoBridge.open(IoBridge.java:442)
E/SELENDROID( 2480): 	... 6 more
I/art     ( 2480): System.exit called, status: -1
I/AndroidRuntime( 2480): VM exiting with result code -1, cleanup skipped.
W/InputDispatcher( 1217): channel 'e25c616 enps.mobile.enpsmobilewrapper/enps.mobile.enpsmobilewrapper.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
E/InputDispatcher( 1217): channel 'e25c616 enps.mobile.enpsmobilewrapper/enps.mobile.enpsmobilewrapper.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
W/InputDispatcher( 1217): channel '1cd2b17f enps.mobile.enpsmobilewrapper/enps.mobile.enpsmobilewrapper.WebViewActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
E/InputDispatcher( 1217): channel '1cd2b17f enps.mobile.enpsmobilewrapper/enps.mobile.enpsmobilewrapper.WebViewActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
I/Zygote  (  933): Process 2480 exited cleanly (255)
I/ActivityManager( 1217): Process enps.mobile.enpsmobilewrapper (pid 2480) has died
W/ActivityManager( 1217): Force removing ActivityRecord{1a6dcefa u0 enps.mobile.enpsmobilewrapper/.WebViewActivity t6}: app died, no saved state
I/WindowState( 1217): WIN DEATH: Window{e25c616 u0 enps.mobile.enpsmobilewrapper/enps.mobile.enpsmobilewrapper.MainActivity}
W/InputDispatcher( 1217): Attempted to unregister already unregistered input channel 'e25c616 enps.mobile.enpsmobilewrapper/enps.mobile.enpsmobilewrapper.MainActivity (server)'
I/WindowState( 1217): WIN DEATH: Window{1cd2b17f u0 enps.mobile.enpsmobilewrapper/enps.mobile.enpsmobilewrapper.WebViewActivity}
W/InputDispatcher( 1217): Attempted to unregister already unregistered input channel '1cd2b17f enps.mobile.enpsmobilewrapper/enps.mobile.enpsmobilewrapper.WebViewActivity (server)'
W/ActivityManager( 1217): Force removing ActivityRecord{e20ab54 u0 enps.mobile.enpsmobilewrapper/.MainActivity t6}: app died, no saved state
W/ActivityManager( 1217): Crash of app enps.mobile.enpsmobilewrapper running instrumentation ComponentInfo{io.selendroid.enps.mobile.enpsmobilewrapper/io.selendroid.server.ServerInstrumentation}
I/ActivityManager( 1217): Force stopping enps.mobile.enpsmobilewrapper appid=10057 user=0: finished inst
Feb 27, 2015 10:47:38 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: /Users/todorov/Library/Android/sdk/platform-tools/adb -s emulator-5560 shell ps
Feb 27, 2015 10:47:38 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->
USER     PID   PPID  VSIZE  RSS     WCHAN    PC        NAME
root      1     0     2936   804   c02b4929 0806bca0 S /init
root      2     0     0      0     c023172d 00000000 S kthreadd
root      3     2     0      0     c021f68a 00000000 S ksoftirqd/0
root      4     2     0      0     c022e172 00000000 S kworker/0:0
root      5     2     0      0     c022e172 00000000 S kworker/u:0
root      6     2     0      0     c022dc18 00000000 S khelper
root      7     2     0      0     c022e172 00000000 S kworker/u:1
root      237   2     0      0     c028ecb8 00000000 S sync_supers
root      239   2     0      0     c028f839 00000000 S bdi-default
root      241   2     0      0     c022dc18 00000000 S kblockd
root      249   2     0      0     c022dc18 00000000 S ata_sff
root      260   2     0      0     c04f6ea7 00000000 S khubd
root      265   2     0      0     c022dc18 00000000 S md
root      279   2     0      0     c022e172 00000000 S kworker/0:1
root      280   2     0      0     c022dc18 00000000 S cfg80211
root      393   2     0      0     c02893f8 00000000 S kswapd0
root      462   2     0      0     c02d3c86 00000000 S fsnotify_mark
root      482   2     0      0     c022dc18 00000000 S crypto
root      569   2     0      0     c022dc18 00000000 S iscsi_eh
root      590   2     0      0     c048c58e 00000000 S mtdblock0
root      598   2     0      0     c048c58e 00000000 S mtdblock1
root      606   2     0      0     c048c58e 00000000 S mtdblock2
root      676   2     0      0     c022dc18 00000000 S binder
root      697   2     0      0     c022dc18 00000000 S deferwq
root      698   1     2932   664   c02b4929 0806bca0 S /sbin/ueventd
root      899   2     0      0     c032aabb 00000000 S jbd2/mtdblock0-
root      900   2     0      0     c022dc18 00000000 S ext4-dio-unwrit
root      904   2     0      0     c02c461b 00000000 S flush-31:1
root      906   2     0      0     c032aabb 00000000 S jbd2/mtdblock1-
root      907   2     0      0     c022dc18 00000000 S ext4-dio-unwrit
root      910   2     0      0     c02c461b 00000000 S flush-31:2
root      912   2     0      0     c032aabb 00000000 S jbd2/mtdblock2-
root      913   2     0      0     c022dc18 00000000 S ext4-dio-unwrit
logd      914   1     13964  2480  ffffffff b76d4a91 S /system/bin/logd
root      915   1     4000   440   c02d65b4 080959e5 S /sbin/healthd
root      916   1     5804   1404  c02d65b4 b774ec05 S /system/bin/lmkd
system    917   1     3844   832   c056a888 b7690046 S /system/bin/servicemanager
root      918   1     9408   2100  ffffffff b76916d1 S /system/bin/vold
system    919   1     58336  3988  ffffffff b7754f16 S /system/bin/surfaceflinger
root      921   1     3708   692   c02d65b4 b7694c05 S /system/bin/qemud
shell     924   1     3980   1032  c03ec8a7 b7642f16 S /system/bin/sh
root      925   1     10112  544   ffffffff 0806b836 R /sbin/adbd
root      926   1     13800  1680  ffffffff b76476d1 S /system/bin/netd
root      927   1     4616   1048  c0578210 b77494e3 S /system/bin/debuggerd
radio     928   1     9276   1700  ffffffff b76ee6d1 S /system/bin/rild
drm       929   1     15804  3896  ffffffff b7681046 S /system/bin/drmserver
media     930   1     110596 9756  ffffffff b769a046 S /system/bin/mediaserver
install   931   1     3860   852   c05e4fab b770df16 S /system/bin/installd
keystore  932   1     7828   2180  c056a888 b7661046 S /system/bin/keystore
root      933   1     536068 50152 ffffffff b76ae865 S zygote
root      940   2     0      0     c0254840 00000000 S kauditd
system    1217  933   699940 106212 ffffffff b76aec05 S system_server
u0_a13    1298  933   597936 71420 ffffffff b76aec05 S com.android.systemui
u0_a31    1331  933   580132 49100 ffffffff b76aec05 S com.android.inputmethod.latin
u0_a7     1354  933   761340 61000 ffffffff b76aec05 S com.google.android.gms
radio     1396  933   545296 30796 ffffffff b76aec05 S com.android.server.telecom
radio     1414  933   569692 45820 ffffffff b76aec05 S com.android.phone
u0_a8     1431  933   578324 61464 ffffffff b76aec05 S com.android.launcher
u0_a2     1544  933   549556 35180 ffffffff b76aec05 S android.process.acore
u0_a7     1643  933   645532 57792 ffffffff b76aec05 S com.google.process.location
u0_a7     1663  933   635532 53600 ffffffff b76aec05 S com.google.process.gapps
u0_a7     1748  933   616920 34116 ffffffff b76aec05 S com.google.android.gms.ui
u0_a7     1776  933   617944 36696 ffffffff b76aec05 S com.google.android.gms.wearable
u0_a22    1849  933   547868 31176 ffffffff b76aec05 S com.android.deskclock
u0_a36    1895  933   544308 29008 ffffffff b76aec05 S com.android.music
root      1909  925   3616   812   c0578210 b7722743 S logcat
system    1924  933   542392 26108 ffffffff b76aec05 S com.android.keychain
u0_a4     1939  933   548848 28020 ffffffff b76aec05 S com.android.dialer
u0_a5     1948  933   551020 35540 ffffffff b76aec05 S android.process.media
u0_a1     1994  933   547788 32152 ffffffff b76aec05 S com.android.providers.calendar
u0_a9     2020  933   543280 26360 ffffffff b76aec05 S com.android.managedprovisioning
u0_a10    2044  933   552292 32720 ffffffff b76aec05 S com.android.mms
u0_a18    2138  933   552468 31464 ffffffff b76aec05 S com.android.calendar
u0_a26    2179  933   561192 36720 ffffffff b76aec05 S com.android.email
u0_a28    2196  933   549872 29196 ffffffff b76aec05 S com.android.exchange
u0_a25    2239  933   546992 28364 ffffffff b76aec05 S com.android.documentsui
u0_a6     2266  933   542356 26492 ffffffff b76aec05 S com.android.externalstorage
u0_a7     2310  933   623364 46604 ffffffff b76aec05 S com.google.android.gms.unstable
root      2392  925   3616   832   c0578210 b76cf743 S logcat
root      2504  925   3616   808   c0578210 b76cb743 S logcat
root      2562  925   5708   1100  00000000 b7684f16 R ps
<--

**Comment by attodorov** [comment]
The issue I am facing turned out to be different, unrelated to switching of the window. It was just that this was the next call in the code that made me think it was the culprit. My app was crashing because of the following line:

new Actions(driver).SendKeys("\uE100").Perform();

Thanks
Angel

**Comment by majun8cn** [comment]
Hi all,
I found the ROOT cause. 
It happened due to this commit https://github.com/selendroid/selendroid/commit/7e24a462fbdeae819c3219f5c4f8bd907942a6a8

This commit introduces a new ExtendedChromeClient and provides the support for Cordova 3.7. 
-          chromeClient = new SelendroidWebChromeClient();
+          //chromeClient = new SelendroidWebChromeClient();
+          if (view instanceof CordovaWebView) {
+            CordovaWebView webview=(CordovaWebView)view;
+            CordovaInterface ci=null;
+            chromeClient = new ExtendedCordovaChromeClient(null,webview);
+          } else {
+            chromeClient = new SelendroidWebChromeClient();
+          }
           view.setWebChromeClient(chromeClient);

For me, because we are using the Cordova 2.X, the new Cordova library may not work well with my Cordova based app. If you comment out the above code and use only SelendroidWebChromeClient() as the chromeClient. The new code (0.16.SNAPSHOT) can work with switching webview. It does not crash. 

Can the Selendroid fix this and add the legacy test for old Cordova libraries?

I can help if needed.

**Comment by fayizkc** [comment]
I have no issue with version 15 :)

**Comment by Zhanglii** [comment]
I can still reproduce this issue on 0.15. Did we already fix this?

**Comment by MartinoMensio** [comment]
when calling switchTo().window("WEBVIEW") i get:
 java.lang.VerifyError: Verifier rejected class io.selendroid.server.model.SelendroidWebDriver$4 due to bad method void io.selendroid.server.model.SelendroidWebDriver$4.run() (declaration of 'io.selendroid.server.model.SelendroidWebDriver$4' appears in /data/app/io.selendroid.com.myapp-1/base.apk)

using selendroid 0.15

**Comment by MartinoMensio** [comment]
Looking at logcat i see:
I/art     (13699): void io.selendroid.server.model.SelendroidWebDriver$4.run() failed to verify: register v5 has type Precise Reference: io.selendroid.server.model.SelendroidWebDriver$ExtendedCordovaChromeClient but expected Reference: android.webkit.WebChromeClient

Please help me

**Comment by jackie-chan** [comment]
Hi,
I'm getting this issue right now as well. Our app is built on Cordova 2.x and when switching to webview, the app crashes with the following error:

```
java.lang.NoSuchMethodError: org.apache.cordova.CordovaChromeClient.<init>
	at io.selendroid.server.model.SelendroidWebDriver$ExtendedCordovaChromeClient.<init>(SelendroidWebDriver.java:515)
	at io.selendroid.server.model.SelendroidWebDriver$4.run(SelendroidWebDriver.java:351)
	at android.os.Handler.handleCallback(Handler.java:615)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4921)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
	at dalvik.system.NativeStart.main(Native Method)
```

Can this be fixed?

**Comment by MartinoMensio** [comment]
Hi. I found no way to fix that. They suggested me to recompile Selendroid with the version of Cordova used in my project, but i'm not able to do that

**Comment by zeeshanjan82** [comment]
I am also getting the same issue with selendroid version 0.17
