### ISSUE TITLE
Save screenshot of fuill screen using selendroid

### ISSUE THREAD

**Issue by aik1771** [selendroid/selendroid#857]
Using selendroid

When using driver.save_screenshot "./#{Time.now.strftime("mobile_portrait_Android_login1_%d_%m_%Y__%H_%M_%S")}.png"

I'm unable to take entire screenshot... only take a screenshot of what I see on the device..

**Comment by lukeis** [comment]
we won't be fixing this, I believe mainly because this is how the android mechanisms that we use to take screenshots work. Also the selenium api does not require / guarantee Full Canvas screenshots.

https://w3c.github.io/webdriver/webdriver-spec.html#screenshots

"Note that the WebDriver spec does not provide a mechanism for taking a screenshot of the entire screen."
