### ISSUE TITLE
TestWaiter.waitForElement no longer working

### ISSUE THREAD

**Issue by metasonic** [selendroid/selendroid#947]
TestWaiter.waitForElement doesn't seem to working the new selendroid release, 0.16.
In the same setup the method is working perfectly using selendoid 0.15 but now i am no longer able to find the element.

Please not that I am starting the server as a WebDriver instance not a SelendroidDriver one, so i have something like 
SelendroidDriver newInstance = SelendroidDriver(capabilities);
WebDriver instance = newInstance ;

PS. If the device has selendroid 0.13 SNAPSHOT and i use the new selendroid build everything is working as expected, so maybe the issue is related to the new snapshot?

**Comment by asm89** [comment]
That specific code hasn't changed since `0.13.0`. In `0.16.0` there was one change that I think might affect you: https://github.com/selendroid/selendroid/pull/895. The implicit wait timeout on the device was changed from 5 seconds to 0 seconds. The link contains information on how to restore the old behavior. You should probably just make the timeout in your `TestWaiter.waitForElement()` calls a bit longer.

If you still see the issue please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

**Comment by metasonic** [comment]
Hello,  opened issue https://github.com/selendroid/selendroid/issues/953 for this,  added a test showing the issue,  i'm testing on a hybrid app.
