### ISSUE TITLE
Google Maps apps is crashing While try to installing with selendroid

### ISSUE THREAD

**Issue by ssirekumar** [selendroid/selendroid#959]
Hi Team,

I very good impressive with the selendroid updates. Recently i got an issue with one of the most known application of google maps apk file. When i try to install this app with selendroid the app is launched but its crashes. The reason behind this, selendroid is resigning the original apk file into with new apk file. But this certificates are does not matching with 'google play services'. Due to this the maps is crashing when it launches. I am looking for some good solution for this. This will give some achievement in my project towards the automation side. So could you please provide some solution for this.

Excuse me if i wrongly posted here.

**Comment by lukeis** [comment]
Selendroid works by resigning the app under test with the same certificate as the 'selendroid.apk' and thus we are allowed to automate / cross the app boundary in android.

If the app doesn't work because it needs a specific certificate signed with it, then you would need to sign selendroid with that same certificate. You would do this by using the -keystore (and probably -keystorePassword) options.

If you do not have access to this certificate, then I'm afraid you won't be able to automate the app. In this case with running google maps, you would need to work at google :)

Another option for google maps would be to use your own app that uses google map's APIs and then automate that app.

**Comment by ssirekumar** [comment]
Thanks lukeis for the information..
