### ISSUE TITLE
Selendroid as a Maven Dependency

### ISSUE THREAD

**Issue by Danlock** [selendroid/selendroid#999]
I am leaving this mostly as a help for Java developers who may had trouble getting Selendroid standalone  added to their project as a maven dependency, and got NoClassDefFound exceptions.

Add     
<dependency>
		<groupId>org.apache.commons</groupId>
		<artifactId>commons-exec</artifactId>
		<version>1.3</version>
	</dependency>

to you pom.xml to fix this problem. This is especially relevant if you are getting weird errors like NoClassDefFound. 

The issue i want to bring up for the selendroid team is that this maven dependency should have been included with the selendroid-standalone dependency to avoid this particular problem in the first place. I looked at your pom and you guys only have version 1.1, which seems to be causing the problem.

**Comment by lukeis** [comment]
seems like you potentially had a dependency convergence issue?

But we're in the process of moving to gradle now - https://github.com/selendroid/selendroid/pull/998
and in that PR it's updating commons-exec to 1.3

So... I don't think we're going to 'fix' the maven parts, since the next release will likely be done with gradle. Going to close this issue for that reason.
